### ISSUE TITLE
Require phone numbers for orders

### ISSUE THREAD

**Issue by omzlo** [omzlo/lektronz-marketplace#1]
I ship via stamps.com and I have to have a phone number for the customer in order to print the label and ship items internationally.

Is it possible to require the customers phone number for orders? 

(copied from #feature-request, testing git hub integration)

**Comment by TweetyDaBird** [comment]
Can we add that it needs to include country code etc, in standard format, so all tax/duty forms accept it?

**Comment by omzlo** [comment]
This should be implemented now. Phone numbers must now be either:
* In international format (e.g. +44 20 5551 1223)
* American format (e.g. (650) 253-0001).

They are normalised to the international format.

**Comment by ArnieO** [comment]
> This should be implemented now. Phone numbers must now be either:
> 
>     * In international format (e.g. +44 20 5551 1223)
> 
>     * American format (e.g. (650) 253-0001).
> 
> 
> They are normalised to the international format.

Great! But please store the numbers without spaces. If not, I will have to remove spaces for every single order when I transfer the phone number to the customs declaration (which in my case is too dumb to filter out spaces).

**Comment by omzlo** [comment]
The phone is stored internally without spaces in the in E.164 format (at least for new orders), and is also now displayed that way in the "copy and paste" section. In invoices, it is formatted and printed with spaces.
