### ISSUE TITLE
One-click Batch Printing for Invoices

### ISSUE THREAD

**Issue by qwertymodo** [omzlo/lektronz-marketplace#10]
**Is your feature request related to a problem? Please describe.**
If a large number of orders comes in at once, it is somewhat annoying to have to click through each order, scroll halfway down the page to customer invoice, click the button, then click print on the popped-up tab.

**Describe the solution you'd like**
Add a button or link on the orders list page which generates a multi-page print job containing all of the customer invoices for all currently unshipped orders.

**Describe alternatives you've considered**
A simpler improvement would be to just move the customer invoice button up on the order screen so you don't have to scroll down to it, or maybe add a button on the orders list page so you can directly open the customer invoice in one click instead of having to click the order and then click the invoice.

**Comment by ArnieO** [comment]
Good request, it would be great to collect a number of invoices in one PDF.

**Comment by omzlo** [comment]
If you click "Unfulfilled orders" in the seller UI, there's a button at the bottom of the page to do that. 
This is experimental for now because we need to see how it impacts server performance. We might need to rework it to run as a background job.

**Comment by ArnieO** [comment]
> If you click "Unfulfilled orders" in the seller UI, there's a button at the bottom of the page to do that.

Great - I will start using this from now on! 😃
