### ISSUE TITLE
Add rate limitation for some API calls.

### ISSUE THREAD

**Issue by omzlo** [omzlo/lektronz-marketplace#13]
Calls to the API shipping should be rate-limited (e.g. 5 times per day) to avoid flooding the customer with emails if the app driving the API goes in a loop.

**Comment by arturo182** [comment]
Per order I hope 😅

**Comment by omzlo** [comment]
Per order indeed.

**Comment by qwertymodo** [comment]
Is there any valid use case for sending more than one shipping notification email? I think this is a case that calls for idempotency, ie once the order is marked shipped, marking it shipped a second time shouldn't do anything at all (unless the content of the second call changes something, like a different tracking number).

**Comment by omzlo** [comment]
The main reason to allow multiple calls to the shipping API is to permit the seller to make changes/corrections to the tracking information. But realistically, this should not happen more than 2, 3 or maybe 4 times.

**Comment by qwertymodo** [comment]
Ok, so it should be possible to make changes, that makes sense, but repeated calls with the same exact information should essentially just be ignored. They shouldn't get logged as order updates, and they shouldn't trigger new emails, unless you actually change something. I think that would be a more complete and correct solution to the problem than rate limiting, which only slows the problem down.  Obviously, I have issues that I need to address client side, but from an API design standpoint, repeatedly sending the same exact write request should only trigger the expected event/trigger/action/state change/etc once.

**Comment by omzlo** [comment]
> Ok, so it should be possible to make changes, that makes sense, but repeated calls with the same exact information should essentially just be ignored. They shouldn't get logged as order updates, and they shouldn't trigger new emails, unless you actually change something. I think that would be a more complete and correct solution to the problem than rate limiting, which only slows the problem down. Obviously, I have issues that I need to address client side, but from an API design standpoint, repeatedly sending the same exact write request should only trigger the expected event/trigger/action/state change/etc once.

That's a very good point. We will do what you suggest.
