### ISSUE TITLE
Country restriction by product

### ISSUE THREAD

**Issue by mayermakes** [omzlo/lektronz-marketplace#18]
**Is your feature request related to a problem? Please describe.**
Not all products/devices can legally be sold in every country you ship to. 
Same for options. Reasons can be shipping restrictions, paperwork like certifications etc.

**Describe the solution you'd like**
the ability to enable the shipping regions defined under shipping per product.

**Describe alternatives you've considered**
Gaming the system by using an arbitrary weight for a shipping rate that will only be triggered by this product. not the intention of the weight system at all.

**Additional context**

**Comment by mayermakes** [comment]
Pushing this because of pressing regulatory implementations.
We really need to be able to set locations we can sell to on a product/item basis. 
This is crucial for compliancy with current CE and Waste management regulation.

**Comment by omzlo** [comment]
This is now implemented in beta. Go to the shipping tab in the seller dashboard and scroll to:

![Screenshot 2024-04-10 at 6 51 37 PM](https://github.com/omzlo/lektronz-marketplace/assets/26352074/8225c8d4-c29c-4a83-a884-1927dcb240e9)
