### ISSUE TITLE
Bug: Order history showing wrong value

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#2]
Order history
Event
Date
Information
Payment success
11 Nov 2022, 09:11 CET

{"id":"pi_3M2qLs2c6KVQolYm1j5H0MHG","object":"payment_intent","amount":4796,"amount_capturable":0,"amount_details":{"tip":{}},"amount_received":4796,"application":"ca_Je0i7tmQ85KXGEkfOCbjDxscOCR06Fsj","application_fee_amount":240,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[{"id":"ch_3M2qLs2c6KVQolYm1PMdcWzL","object":"charge","amount":4796,"amount_captured":4796,"amount_refunded":0,"application":"ca_Je0i7tmQ85KXGEkfOCbjDxscOCR06Fsj","application_fee":"fee_1M2qN62c6KVQolYmm4HGmxvJ","application_fee_amount":240,"balance_transaction":"txn_3M2qLs2c6KVQolYm1989MqUM","billing_details":{"address":{"city":null,"country":"CA","line1":null,"line2":null,"postal_code":"V7K 

Continued...

**Comment by omzlo** [comment]
This issue should now be fixed.
