### ISSUE TITLE
Add a button to return to products page from a product listing

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#20]
**Is your feature request related to a problem? Please describe.**
When editing small details of the products, once I hit update and view the changes, I find myself having to go to the menu -> my store, then to the sidebar -> products, clicking on several places to return to the listing of products. And doing this several times become annoying.

**Describe the solution you'd like**
Add a button to the top where edit/retire etc. is, that takes me back to the products tab.

**Comment by omzlo** [comment]
This has been implemented ("My product list")

![Screenshot 2023-09-11 at 3 43 13 PM](https://github.com/omzlo/lektronz-marketplace/assets/26352074/ed6ca6f2-8be8-410d-8a55-95b8243b843e)
