### ISSUE TITLE
Price shown for extras doesn't take volume discount into consideration.

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#23]
**When adding a quantity of items as extras, the price shown is calculated of the single item price, not accounting for volume discounts.**
As a result, for example the price shown for adding 60x LED's to the kit in my shop displays as ~$70 while the price taking volume discounts into account is ~$17. This would likely deter people from considering to buy the items unless they click on them and get the correct price displayed.

**Describe the solution you'd like**
Hopefully have the pricing calculation updated to include volume discounts.

**Comment by omzlo** [comment]
Fixed
