### ISSUE TITLE
For IOSS-sellers, customers must declare as Business or Consumer

### ISSUE THREAD

**Issue by ArnieO** [omzlo/lektronz-marketplace#26]
**Is your feature request related to a problem? Please describe.**
We had a case where a shipment registered as IOSS (VAT prepaid) was charged with VAT + customs fee because customer had registered company name in the "Organization" field, and it was used in the customs declaration as first address line.

IOSS only applies to B2C e-commerce, ref: https://vat-one-stop-shop.ec.europa.eu/index_en

**Describe the solution you'd like**
Business customers shall not prepay VAT. If seller is outside EU, they will be charged with VAT + customs fee when goods arrive in destination country. The platform should handle this correctly, both for registered and non-registered customers

**Describe alternatives you've considered**
An alternative could be to remove the "Organization" field, which would implicitly signal that Lectronz only sells to Consumers - not to Business customers.
I see two issues with this:

1. There is a risk that Business customers would enter company name as first address line. Result: They prepay VAT, and could be re-charged VAT + customs fee when goods arrives in destination country.
2. Some sellers have a fair amount of Business customers. They should be handled correctly, receiving an Invoice issued to company name. (No prepaid VAT)

**Additional context**
If seller is outside EU, business customer should probably get a warning in the checkout process that they must expect to be charged with VAT + customs fee when goods arrive in their country.

**Comment by omzlo** [comment]
Sellers can now declare themselves as a "business" during checkout. 

![Screenshot 2024-02-02 at 11 58 06 AM](https://github.com/omzlo/lektronz-marketplace/assets/26352074/85ca7ff7-036a-4472-8322-774cad7d3b3d)
