### ISSUE TITLE
Bug: Order overview is showing option headers instead of selected option.

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#3]
Details
Product
Quantity
Unit price
Total

[RGB LED - SK6812 mini-E](https://lectronz.com/products/rgb-led-sk6812-mini-e) (SKU: SK6812_mini-E)
58
€0.44
€25.52

[Socket kit for controller](https://lectronz.com/products/socket-kit-for-controller)
**Add soldering pins: Add soldering pins
Controller Type: Controller Type (SKU: SOCKET_MCU_12)**
2
€4.50
€9.00

**Comment by omzlo** [comment]
This should now be fixed.
