### ISSUE TITLE
Updates to product page sorting

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#30]
As it is now, you can sort the products by name **OR** by status etc. I would very much like to be able to sort them by name **AND** status for example. Ie, sorting them by name inside the status sort (bubble sort).

Alternatively, move retired (and also under review/draft?) products to new headers/sections, meaning they are present, but not in the way of your default view.

**Comment by omzlo** [comment]
The new product tagging feature should help help here.

**Comment by TweetyDaBird** [comment]
It does help, closing this as finished!
