### ISSUE TITLE
A way to easily duplicate a product

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#31]
If for instance you are selling a prototype/scratch&dent/whatever usually one-off version of an existing product, it would be useful to have a way of easily duplicating that product, add a descriptive line or two, or make a small edit/set price, and make it sellable/for review.

Also, it _may_ be a good idea to somehow mark these as being 'one-off' or similar, and then make them disappear from the list of retired products after a set timeline, like 90 days or similar, reducing clutter. Obviously, this part is far less important, if it creates back-end problems I cannot foresee.

**Comment by omzlo** [comment]
Now you can duplicate products, in the product edit page.
![Screenshot 2024-04-24 at 8 53 48 AM](https://github.com/omzlo/lektronz-marketplace/assets/26352074/38bf6e76-3f3f-4e7e-b8ec-7562789d165e)
