### ISSUE TITLE
Set stock_available for product_options via the API

### ISSUE THREAD

**Issue by 30350n** [omzlo/lektronz-marketplace#33]
**Is your feature request related to a problem? Please describe.**

I'm currently working on [integrating Lectronz into InvenTree](https://github.com/30350n/inventree_lectronz) and would like to enable the user to link their stock levels to Lectronz (so that when new stock items get added, the stock level at Lectronz gets set accordingly).

This is already possible via the `PATCH /api/v1/products/{id}` API call, but only per product, not per product option.

**Describe the solution you'd like**

Enable the `PATCH /api/v1/products/{id}` API call to accept additional inputs like so:

- `product_options` **array of object**
  *List of options available for the product.*
  - `id` **integer**
    *Unique identifier for this product option.*
  - `choices` **array of object**
    *Available choices for the option.*
    - `id` **integer**
      *Unique identifier for this choice.*
    - `stock_available` **number**
      *Stock available for this choice.*

To be able to set the stock_available for each product option / choice.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by omzlo** [comment]
This is now available through a distinct API endpoint: see https://lectronz.com/api_docs/product_option_choices

**Comment by 30350n** [comment]
That's perfect, thanks a lot!
