### ISSUE TITLE
Request to update wording for vacation mode,

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#34]
**Is your feature request related to a problem? Please describe.**
The wording on vacation mode is a bit too vague, or outright incorrect. An example below.

"Please note that this store is currently in vacation mode. All orders received since March 11, 2024 will be shipped after March 17, 2024."

This makes it seem that all orders (potentially) will ship on March 17 or perhaps March 18. (No, most would not interpret it like that, but it opens up for that interpretation unfortunately.)

**Describe the solution you'd like**
A better way to word it might be similar to this:

"Please note that this store is currently in vacation mode. All orders received since March 11, 2024 *will be processed after March 17, 2024 and will ship shortly there after.*" Or "*and will ship with normal handling time there after.*"

**Comment by omzlo** [comment]
The wording has now been changed to "Please note that this store is currently in vacation mode. All orders received since March XX, 2024 will be processed after March ZZ, 2024, and shipping will resume thereafter. Thank you for your understanding."
