### ISSUE TITLE
A way to explicitly order the item in the store.

### ISSUE THREAD

**Issue by TweetyDaBird** [omzlo/lektronz-marketplace#37]
**Is your feature request related to a problem? Please describe.**
Right now the items are ordered  alphabetically, which means some of my main products end up on the second page, and some of the smaller extra parts end up way ahead in the listings and on the front page. 
 
**Describe the solution you'd like**
The best solution would be to allow the seller to explicitly order the items in the store.

**Describe alternatives you've considered**
If an explicit order cannot/should not be implemented, ordering thgem by category, as 'main product' 'accessory' and 'sale item' etc, would work.

**Comment by ArnieO** [comment]
Good idea.

**Comment by omzlo** [comment]
We added the ability to tag products with arbitrary tags. Then, in the product index, you can choose to display only the products that match a specific tag. This should help.

**Comment by TweetyDaBird** [comment]
> We added the ability to tag products with arbitrary tags. Then, in the product index, you can choose to display only the products that match a specific tag. This should help.

Unfortunately this is entirely unhelpful. I mean it sort of solves an issue for me personally. But it in no way solves the issue that a potential customer viewing my storefront is shown the accessory products before the active main product based solely on alphabetical sorting.

**Comment by omzlo** [comment]
Oh I see.

**Comment by omzlo** [comment]
So we have a new beta feature that allows storefront customization. It should be activated for @TweetyDaBird 's store.

**Comment by TweetyDaBird** [comment]
With this open for all users, It's done! thank you!
