### ISSUE TITLE
Add price to COMING SOON products

### ISSUE THREAD

**Issue by arturo182** [omzlo/lektronz-marketplace#39]
The price is not secret when you go to the product's page, so don't think it should be secret in the search results as well:

![image](https://github.com/user-attachments/assets/f1ee6f69-e9ce-4b57-a1cc-039cb585f32c)

Also maybe the COMING SOON text should not be rd but like orange or something. We already use red for SOLD OUT.

**Comment by omzlo** [comment]
![Screenshot 2024-09-04 at 11 42 21 AM](https://github.com/user-attachments/assets/dc72461a-9837-44f2-81bd-14f900056541)

Done
