### ISSUE TITLE
Support for "private link" products / previews

### ISSUE THREAD

**Issue by s-ol** [omzlo/lektronz-marketplace#9]
**Is your feature request related to a problem? Please describe.**
I'd like to offer a preview version of a product only to a limited audience of people that I have an existing communications channel with.
I think this could also be useful in other situations, especially for people experimenting with different business models, for example:
- external waiting list or order queuing system
- supporter-only shop (for people who run a patreon for example: [a](https://www.patreon.com/posts/patreon-secret-51897402), [b](https://www.patreon.com/posts/welcome-to-my-14818006))
- or just banally sharing the product page with someone for feedback before launching

**Describe the solution you'd like**
When editing a product that hasn't yet been published, there could be a radio selection "Visibility (after approval):"
- Public
- Private Link Only

Once the product is approved, this can be changed from "private link only" to "public" (and maybe also back? not sure about this).

When the product is "private link only":
- no announcement, re-stock tweets should be sent
- the product shouldn't be visible in the "new releases", store profile, search, etc views
- maybe the URL slug should contain a random unique string at the end
  - if "private link only" can be turned on and off, then this allows regenerating the link as well

I'm not sure how this feature would interact with the "waiting list". Maybe the waiting list should be disabled for private products?

**Describe alternatives you've considered**
An alternative solution to the "alternative business model" idea could be items that can be bought **only with a specific discount code**. It would be strange to end up on such a product page via the "new releases" or an automated twitter post though.

**Comment by ArnieO** [comment]
I think this is a very interesting proposition!

**Comment by omzlo** [comment]
This is more or less implemented now.

**Comment by s-ol** [comment]
Awesome! Thank you 🙂
